//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WatchReminder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class URLs_film
    {
        public int ID_URL { get; set; }
        public int ID_film { get; set; }
        public string URL { get; set; }
    
        public virtual Film Film { get; set; }
    }
}
